services:
  # Servicio de la aplicación Laravel (usando imagen de Docker Hub)
  app:
    image: imorlab/laravel-scaffolding:latest
    container_name: laravel-scaffolding-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel_scaffolding
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
      - REDIS_HOST=redis
      - APP_KEY=base64:Rq/Rr/mDA1w4vXOpjPOAp3U1vyBZXJpVcjRbcMiDWKE=
    volumes:
      - app_public:/var/www/public
    depends_on:
      - db
      - redis
    networks:
      - laravel-network

  # Servidor web Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel-scaffolding-webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - app_public:/var/www/public:ro
    depends_on:
      - app
    networks:
      - laravel-network

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: laravel-scaffolding-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel_scaffolding
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_USER: laravel_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel-network

  # Cache Redis
  redis:
    image: redis:alpine
    container_name: laravel-scaffolding-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-scaffolding-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - laravel-network

# Volumes
volumes:
  dbdata:
    driver: local
  app_public:
    driver: local

# Networks
networks:
  laravel-network:
    driver: bridge
